baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Unicorns Fart Pixels"
paginate = 10
paginatePath = "page"
googleAnalytics = "UA-108727696-1"

[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "archives"
    identifier = "archives"
    url = "/archives/"
[[menu.main]]
    name = "quicktips"
    identifier = "quicktips"
    url = "/quicktips/"
[[menu.main]]
    name = "contact"
    identifier = "contact"
    url = "/contact/"

[taxonomies]
  tag = "tags"